config/routes.rb
Rails.application.routes.draw do
  resources :oenologists
  resources :magazines
  devise_for :users
  resources :strains
  resources :wines
  root 'wines#index'
end

app/models/oenologist.rb
class Oenologist < ApplicationRecord
    has_many :oenologist_magazines, dependent: :destroy
    has_many :magazines, through: :oenologist_magazines
    has_many :grades
    has_many :wines, through: :grades
    #Que acepte los atributos anidados
    accepts_nested_attributes_for :oenologist_magazines,reject_if: :all_blank, allow_destroy: true
end

app/controllers/oenologists_controller.rb
class OenologistsController < ApplicationController
  before_action :set_oenologist, only: %i[ show edit update destroy ]

  # GET /oenologists or /oenologists.json
  def index
    @oenologists = Oenologist.all
  end

  # GET /oenologists/1 or /oenologists/1.json
  def show
  end

  # GET /oenologists/new
  def new
    @oenologist = Oenologist.new
    #Dada la relacion con su tabla intermedia, va a aceptar atributos nesteados (field_form) y lo va a construir
    @oenologist.oenologist_magazines.build
    @magazines = Magazine.all
  end

  # GET /oenologists/1/edit
  def edit
    @oenologist.oenologist_magazines.build
    @magazines = Magazine.all
  end

  # POST /oenologists or /oenologists.json
  def create
    @oenologist = Oenologist.new(oenologist_params)

    respond_to do |format|
      if @oenologist.save
        format.html { redirect_to @oenologist, notice: "Oenologist was successfully created." }
        format.json { render :show, status: :created, location: @oenologist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @oenologist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /oenologists/1 or /oenologists/1.json
  def update
    respond_to do |format|
      if @oenologist.update(oenologist_params)
        format.html { redirect_to @oenologist, notice: "Oenologist was successfully updated." }
        format.json { render :show, status: :ok, location: @oenologist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @oenologist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /oenologists/1 or /oenologists/1.json
  def destroy
    @oenologist.destroy
    respond_to do |format|
      format.html { redirect_to oenologists_url, notice: "Oenologist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_oenologist
      @oenologist = Oenologist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def oenologist_params
      params.require(:oenologist).permit(:name, :age, :country, oenologist_magazines_attributes: [:magazine_id, :editor, :reviewer, :writer])
    end
end

app/helpers/oenologists_helper.rb
module OenologistsHelper
end

app/views/oenologists/_form.html.erb
<%= form_with(model: oenologist, local: true) do |form| %>
  <% if oenologist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(oenologist.errors.count, "error") %> prohibited this oenologist from being saved:</h2>

      <ul>
      <% oenologist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :age %>
    <%= form.number_field :age, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :country %>
    <%= form.text_field :country, class: 'form-control' %>
  </div>

  <!-- Formulario dentro de otro formulario "Formulario anidado"-->

  <div class="container">
    <div class="form-group">
      <%= form.fields_for :oenologist_magazines do |ff| %>
        <%= render 'oenologist_magazine_fields', f: ff  %>
      <% end %>
    </div>
  </div>

  <!-- Ocupando Cocoon -->
  <div class="links pb-3">
    <%= link_to_add_association 'Add Magazine', form, :oenologist_magazines, class: 'btn btn-primary' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/oenologists/_oenologist_magazine_fields.html.erb
<div class="form-group">
    <%= f.label :magazine_id %>
    <!-- Con esto el edit mantiene los valores originales -->
    <!-- Seteo la variable de instancia @magazines la cual se declara en el controlador oenologist -->
    <%= f.collection_select :magazine_id, @magazines, :id, :name %>
</div>

<div class="form-group">
    <%= f.label :editor %>
    <%= f.check_box :editor %>
</div>

<div class="form-group">
    <%= f.label :reviewer %>
    <%= f.check_box :reviewer %>
</div>

<div class="form-group">
    <%= f.label :writer %>
    <%= f.check_box :writer %>
</div>

app/views/oenologists/edit.html.erb
<h1>Editing Oenologist</h1>

<%= render 'form', oenologist: @oenologist %>

<%= link_to 'Show', @oenologist %> |
<%= link_to 'Back', oenologists_path %>

app/views/oenologists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Oenologists</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Country</th>
      <th>Magazines</th>
      <% if current_user.admin %>
      <th colspan="3"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @oenologists.each do |oenologist| %>
      <tr>
        <td><%= oenologist.name %></td>
        <td><%= oenologist.age %></td>
        <td><%= oenologist.country %></td>
        <td>
          <ul>
            <% oenologist.oenologist_magazines.each do |oe| %>
              <li><%= oe.magazine.name %></li>
              <ul>
                <li>Editor:<%= oe.editor %></li>
                <li>Escritor:<%= oe.writer %></li>
                <li>Critico:<%= oe.reviewer %></li>
              </ul>
            <% end %>

          </ul>
        </td>
        <% if current_user.admin %>
          <td><%= link_to 'Show', oenologist %></td>
          <td><%= link_to 'Edit', edit_oenologist_path(oenologist) %></td>
          <td><%= link_to 'Destroy', oenologist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Oenologist', new_oenologist_path %>

app/views/oenologists/new.html.erb
<h1>New Oenologist</h1>

<%= render 'form', oenologist: @oenologist %>

<%= link_to 'Back', oenologists_path %>

app/views/oenologists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @oenologist.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @oenologist.age %>
</p>

<p>
  <strong>Country:</strong>
  <%= @oenologist.country %>
</p>

<%= link_to 'Edit', edit_oenologist_path(@oenologist) %> |
<%= link_to 'Back', oenologists_path %>