config/routes.rb
Rails.application.routes.draw do
  resources :oenologists
  resources :magazines
  devise_for :users
  resources :strains
  resources :wines
  root 'wines#index'
end

app/models/wine.rb
class Wine < ApplicationRecord
    #Tienes muchas conbinaciones
    has_many :blends, dependent: :destroy
    #Tiene muchas cepas mediante las conbinaciones
    has_many :strains, through: :blends
    has_many :grades, dependent: :destroy
    has_many :oenologist, through: :grades
    #Que acepte los atributos anidados de dos modelos
    accepts_nested_attributes_for :blends, reject_if: :all_blank
    accepts_nested_attributes_for :grades, reject_if: :all_blank
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: %i[ show edit update destroy ]
  skip_before_action :only_admin, only: [:index]

  # GET /wines or /wines.json
  def index
    @wines = Wine.all
  end

  # GET /wines/1 or /wines/1.json
  def show
  end

  # GET /wines/new
  def new
    @wine = Wine.new
    @strains = Strain.all #Opcion 1
    @strains_two = Strain.pluck :name, :id #Opcion 2 - Con pluck extraigo el ID de todas las cepas, primero lo que se va a mostrar y luego lo que se guarde en la bd
    @strains_three = Strain.all
    @wine.blends.build
  end

  # GET /wines/1/edit
  def edit
    @strains = Strain.all #Opcion 1
    @strains_two = Strain.pluck :name, :id #Opcion 2 - Con pluck extraigo el ID de todas las cepas, primero lo que se va a mostrar y luego lo que se guarde en la bd
    @strains_three = Strain.all
    @oenologists = Oenologist.all
  end

  # POST /wines or /wines.json
  def create
    @wine = Wine.new(wine_params)

    respond_to do |format|
      if @wine.save
        format.html { redirect_to @wine, notice: "Wine was successfully created." }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wines/1 or /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to @wine, notice: "Wine was successfully updated." }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1 or /wines/1.json
  def destroy
    @wine.destroy
    respond_to do |format|
      format.html { redirect_to wines_url, notice: "Wine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wine_params
      # Con blends_attributes, llamamos a los atributos de la tabla intermedio
      params.require(:wine).permit(:name, {blends_attributes: [:id, :strain_id, :percentage]}, grades_attributes: [:id, :oenologist_id, :score])
    end
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/wines/_blend_fields.html.erb
<div class="form-group">
    <%= f.label :strain_id %>
    <!-- Opcion 1 - Esta opcion hace un mapeo desde la vista -->
    <%#= f.select :strain_id, options_from_collection_for_select(@strains, :id, :name) %>
    <!-- Opcion 2 -->
    <%#= f.select :strain_id, @strains_two %>
    <!-- Opcion 3 - Recoemndado para que se entienda lo que se esta haciendo-->
    <%#= f.select :strain_id, options_for_select(@strains_two) %>
    <!-- Opcion 4 - Con esto el edit mantiene los valores originales -->
    <%= f.collection_select :strain_id, @strains_three, :id, :name %>
</div>

<div class="form-group">
    <%= f.label :percentage %>
    <%= f.number_field :percentage %>
</div>

app/views/wines/_edit_form.html.erb
<%= form_with(model: wine, local: true) do |form| %>
  <% if wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
      <% wine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <!-- Formulario anidado -->
  <div class="container">
    <%= form.fields_for :blends do |ff| %>
      <%= render 'blend_fields', f: ff  %>
    <% end %>
  </div>
  <!-- Ocupando Cocoon -->
  <div class="links pb-3">
    <%= link_to_add_association 'Add Strain', form, :blends, class: 'btn btn-primary' %>
  </div>

  <!-- Formulario anidado -->
  <div class="container">
    <div class="form-group">
      <%= form.fields_for :grades do |ff| %>
        <%= render 'grade_fields', f: ff  %>
      <% end %>
    </div>
  </div>

  <!-- Ocupando Cocoon -->
  <div class="links pb-3">
    <%= link_to_add_association 'Add Score', form, :grades, class: 'btn btn-primary' %>
  </div>

  <!-- Si omito lo anterior "Add Score", tendria que agregar en el controlador de Wine -->
  <!-- @wine.grades.build -->
  <!-- Pero al editar el vino y si este ya tiene un enologo, se agregaria automaticamente un campo para seleccionar otro enologo -->
  <!-- Para evitar lo anterior, se agrega lo siguiente @wine.grades.build unless @wine.grades.present? y asi, puedi seguir ocupando el "Add Score" en este edit-->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wines/_form.html.erb
<%= form_with(model: wine, local: true) do |form| %>
  <% if wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
      <% wine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <!-- Formulario anidado -->
  <div class="container">
    <%= form.fields_for :blends do |ff| %>
      <%= render 'blend_fields', f: ff  %>
    <% end %>
  </div>

  <!-- Ocupando Cocoon -->
  <div class="links pb-3">
    <%= link_to_add_association 'Add Strain', form, :blends, class: 'btn btn-primary' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wines/_grade_fields.html.erb
<div class="form-group">
    <%= f.label :oenologist_id %>
    <%= f.collection_select :oenologist_id, @oenologists, :id, :name %>
</div>

<div class="form-group">
    <%= f.label :score %>
    <%= f.number_field :score %>
</div>

app/views/wines/edit.html.erb
<h1>Editing Wine</h1>

<%= render 'edit_form', wine: @wine %>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path %>

app/views/wines/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h1>Wines</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Strains</th>
      <th>Grades and Oenologist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wines.each do |wine| %>
      <tr>
        <td><%= wine.name %></td>
        <td>
        <ul>
          <% wine.blends.each do |blend| %>
            <!-- Esta info se trae por medio del modelo -->
            <li> <%= blend.strain.name %> (<%= blend.percentage %>%)</li>
          <% end %>
        </ul>
        </td>
        <td>
            <ul>
            <% wine.grades.each do |grade| %>
              <li><%= grade.oenologist.name %> Calificó con un <%= grade.score %></li>
            <% end %>
            </ul>
        </td>
        <% if current_user.admin %>
          <td><%= link_to 'Show', wine %></td>
          <td><%= link_to 'Edit', edit_wine_path(wine) %></td>
          <td><%= link_to 'Destroy', wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wine', new_wine_path, class: 'btn btn-success' %>

app/views/wines/new.html.erb
<h1>New Wine</h1>

<div class="container">
    <%= render 'form', wine: @wine %>
</div>

<%= link_to 'Back', wines_path %>

app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wine.name %>
</p>

<%= link_to 'Edit', edit_wine_path(@wine) %> |
<%= link_to 'Back', wines_path %>